# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-02 14:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand_name', models.CharField(max_length=30)),
                ('brand_details', models.TextField()),
                ('brand_owner', models.CharField(max_length=30)),
                ('brand_origin', models.CharField(max_length=30)),
                ('release', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('picture', models.ImageField(upload_to='posts/')),
                ('post_caption', models.TextField()),
                ('price', models.IntegerField()),
                ('post', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=30)),
                ('profile_pic', models.ImageField(upload_to='profiles/')),
                ('image', models.ImageField(upload_to='profiles/')),
            ],
        ),
        migrations.AddField(
            model_name='post',
            name='Profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='brands.Profile'),
        ),
        migrations.AddField(
            model_name='post',
            name='brand',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='brands.Brand'),
        ),
    ]
