# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-02 15:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('brands', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='post',
            new_name='released',
        ),
    ]
