# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-02 15:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('brands', '0002_auto_20180602_1840'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='Profile',
            new_name='profile',
        ),
    ]
