# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-03 17:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('brands', '0003_auto_20180602_1853'),
    ]

    operations = [
        migrations.RenameField(
            model_name='brand',
            old_name='release',
            new_name='release_date',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='released',
            new_name='released_date',
        ),
    ]
