# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-04 06:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('brands', '0004_auto_20180603_2035'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='profile',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='brands.Profile'),
            preserve_default=False,
        ),
    ]
